# Generated by Django 5.2.5 on 2025-08-29 12:24

import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Senders',
            },
        ),
        migrations.CreateModel(
            name='Organisers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='organiser_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='organiser_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Organisers',
            },
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_message', models.TextField()),
                ('reveal_date', models.DateField()),
                ('qr_code_url', models.URLField(blank=True, max_length=500, null=True)),
                ('topper_identifier', models.CharField(help_text="Unique code printed on the physical cake topper's QR code.", max_length=100, unique=True)),
                ('max_senders', models.PositiveIntegerField(default=6, help_text='Maximum number of senders allowed to contribute to this story.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='core.organisers')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='StorySenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('uploaded', 'Uploaded Media'), ('revoked', 'Revoked')], default='pending', max_length=50)),
                ('invitation_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_links', to='core.senders')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_links', to='core.stories')),
            ],
            options={
                'verbose_name_plural': 'Story Senders',
                'unique_together': {('story', 'sender')},
            },
        ),
        migrations.CreateModel(
            name='ImageContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='contributions/images/')),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('ignored', 'Ignored')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_contributions', to='core.storysenders')),
            ],
        ),
        migrations.CreateModel(
            name='TextContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('ignored', 'Ignored')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contributions', to='core.storysenders')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='contributions/videos/')),
                ('youtube_video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('ignored', 'Ignored')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_contributions', to='core.storysenders')),
            ],
        ),
    ]
